apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:15
          command: ['sh', '-c', 'sleep 10; until pg_isready -h postgres-service -p 5432 -U postgres; do echo waiting for postgres; sleep 2; done;']
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SPRING_DATASOURCE_PASSWORD
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
      containers:
        - name: backend
          image: hnasri1921/formation-backend:0.0.2  # Replace with your actual image
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 180
            periodSeconds: 20
            failureThreshold: 5
# Triggered by Jenkins at 13 سبتمبر, 2025 CET 03:09:58 م
# Triggered by Jenkins at 15 سبتمبر, 2025 CET 06:13:19 م
# Triggered by Jenkins at lun. 15 sept. 2025 21:16:41 CET
# Triggered by Jenkins at lun. 15 sept. 2025 22:28:01 CET
